# Prefer archive libraries from pkg-config's complete static dependency list.
# Keep the OS ABI libraries shared; Qt and graphics plugins are deployed later.
function(fceux_static_pkg_libraries prefix output)
  set(result)
  foreach(flag IN LISTS ${prefix}_STATIC_LDFLAGS)
    if(flag MATCHES "^-l(.+)$")
      set(name "${CMAKE_MATCH_1}")
      if(name MATCHES "^(SDL2|minizip|archive|z|bz2|lzma|zstd|lz4|nettle|acl)$")
        unset(archive CACHE)
        find_library(archive NAMES "lib${name}.a"
          HINTS ${${prefix}_STATIC_LIBRARY_DIRS})
        if(archive)
          message(STATUS "Static dependency: ${archive}")
          list(APPEND result "${archive}")
          continue()
        elseif(name MATCHES "^(SDL2|minizip|archive|z)$")
          message(FATAL_ERROR "Portable build requires lib${name}.a; install its static development library")
        endif()
      endif()
    endif()
    list(APPEND result "${flag}")
  endforeach()
  set(${output} "${result}" PARENT_SCOPE)
endfunction()
